### ISSUE TITLE
how do i run this thing bruh

### ISSUE THREAD

**Issue by Katerang31** [Neijwiert/Feeder#2]
how to run it when it's feeder-master? theres no run or executables here for the ionjector wth

**Comment by Neijwiert** [comment]
The repo is incomplete and I do not have the code anymore. The basic gist was starting BattleEye in suspended mode, starting ARK in suspended mode, hooking CreateProcess in BattleEye, hooking whatever you need in ARK, resuming BattleEye and finally waiting for CreateProcess call and passing the already created ARK handle.

Now, I do not condone cheating in any way and this was for a private server. I never finished the code anyway, but I was able to get screenshots. I give no guarantees that this wont get you a Steam VAC ban.
